### PR TITLE
Add abyss_orange_mix_3

### PR DESCRIPTION
**Pull request by fumiama**
Since the colab link in the README file are all belongs to @camenduru , I leave it without change. Maybe you can add one row after merging.

### CODE REVIEW

**Comment by camenduru** [comment]
please check this https://github.com/camenduru/stable-diffusion-webui-colab/issues/120

**Comment by fumiama** [comment]
OK. I had missed looking that guide.

**Comment by camenduru** [comment]
I just prepared hehe 😆

**Comment by fumiama** [comment]
> I just prepared hehe 😆

Well, maybe it should be placed at `CONTRIBUTING.md`, where we normally check about.

**Comment by camenduru** [comment]
good idea 🤩 ok I will add

**Pull request closed without merging**
