### PR TITLE
add: abyss_orange_mix_3_webui_colab.ipynb

### PR DESCRIPTION
**Pull request by fumiama**

### CODE REVIEW

**Comment by etherealxx** [comment]
I think for 2.0 you need to add the controlnet part. [Use this as references](https://github.com/camenduru/stable-diffusion-webui-colab/blob/v2.0/abyss_orange_mix_2_webui_colab.ipynb)

**Comment by fumiama** [comment]
> I think for 2.0 you need to add the controlnet part. [Use this as references](https://github.com/camenduru/stable-diffusion-webui-colab/blob/v2.0/abyss_orange_mix_2_webui_colab.ipynb)

fixed.

**Comment by etherealxx** [comment]
v2.0 tested working fine.

**Comment by camenduru** [comment]
@etherealxx, please don't merge if not fixed yet

**Comment by camenduru** [comment]
thanks @fumiama ❤

**Comment by camenduru** [comment]
ok I fixed

**Comment by etherealxx** [comment]
> @etherealxx, please don't merge if not fixed yet

oh, sorry, forgot about that one part.

**Pull request merged**
