### PR TITLE
mouseymix

### PR DESCRIPTION
**Pull request by Cherryblossomoflove**
Let's hope it works, it was confusing!

### CODE REVIEW

**Comment by camenduru** [comment]
Hi @Cherryblossomoflove 👋 please create new file mouseymix_webui_colab.ipynb

**Comment by Cherryblossomoflove** [comment]
> Hi @Cherryblossomoflove 👋 please create new file mouseymix_webui_colab.ipynb

How tho?

**Comment by camenduru** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/120 just copy paste

**Comment by camenduru** [comment]
then change the name to mouseymix_webui_colab.ipynb

**Comment by Cherryblossomoflove** [comment]
> then change the name to mouseymix_webui_colab.ipynb

Like this?
image

**Comment by Cherryblossomoflove** [comment]
> > then change the name to mouseymix_webui_colab.ipynb
> 
> Like this? image

oops my Browers crashed, fixing it

**Comment by camenduru** [comment]
first click this https://github.dev/camenduru/stable-diffusion-webui-colab

**Comment by Cherryblossomoflove** [comment]
> first click this https://github.dev/camenduru/stable-diffusion-webui-colab

okay.. and then?

**Comment by Cherryblossomoflove** [comment]
> > first click this https://github.dev/camenduru/stable-diffusion-webui-colab
> 
> okay.. and then?

oh wait

**Comment by camenduru** [comment]
@Cherryblossomoflove please watch this https://www.youtube.com/watch?v=uzG5mTZxfoE

**Comment by camenduru** [comment]
Hi @Cherryblossomoflove 👋 I tried to merge but this is not possible 😭 you should update your branch first

**Pull request closed without merging**
